### ISSUE TITLE
feature: additional flags (--skip-commit-but-tag, --skip-csproj)

### ISSUE THREAD

**Issue by mumby0168** [versionize/versionize#101]
I have been looking at conventional commits for a while in the .NET space for a while.

I have an idea of how I'd like to implement it but the tools so far haven't had the option set I need, I think with a small set of additional options this library might be able to do what I need.

The idea is that I'd like to use git tags only to manage the versioning and keep the changelog.md files in a repo of it's own. The reason for this is to not have additional release commits in `main`  I'd simply like to trigger a release manually generate the file, push that to another repo and then tag the commit with the new version number via this tool.

In order to do this I'd like an option to skip the auto commit but still perform the git tag, it would also be nice to have to add the additional bits to the csproj, hence the two additional flags I am proposing.

Happy to start working on this is it's suitable for this project?

Thanks,
Billy

**Comment by cabauman** [comment]
> --skip-commit-but-tag

Agreed. I wish `--skip-commit` didn't skip the tagging part. If we make a v2 that will be one breaking change to include.

> The idea is that I'd like to use git tags only to manage the versioning and keep the changelog.md files in a repo of its own.

Yeah, I see where you're coming from. I do the something similar in other repos:

1. Version bump based on the latest version tag.
2. Create a GitHub release (instead of maintaining a changelog.md).
3. Push the new tag (no commit).

> it would also be nice to have to add the additional bits to the csproj

Sorry, I don't understand this statement. Do you mean you want to skip reading/writing the csproj version so you can purely depend on tags? If so, yes, I agree.
